---
title: Klassentoernooi 2017
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Dit is de site van het klassentoernooi van het Barlaeus gymnasium in
  2017.

'
baseurl: 
url: 
repository: klassentoernooi/klassentoernooi.github.io
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
