---
title: Klassentoernooi 2017
timezone: Europe/Amsterdam
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 
baseurl: 
url: 
repository: klassentoernooi/klassentoernooi.github.io
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
